mysql: &MYSQL
  adapter: mysql
  user: 'root'
  password: 'root'
  host: localhost
  port: 3306
  
development:
  <<: *MYSQL
  database: sequencescape_development

production:
  <<: *MYSQL
  database: sequencescape_production
