plate_management:
  - '*.*.plate.createplate'
  - '*.*.plate.create'
  - '*.*.plate.updateplate'
  - '*.*.gel.creategel'
  - '*.*.gel.create'
  - '*.*.gel.updategel'
  - '*.*.gelimage.creategelimage'
  - '*.*.gelimage.create'
  - '*.*.gelimage.updategelimagescore'
  - '*.*.updategelimagescore.updategelimagescore'
  - '*.*.tuberack.createtuberack'
  - '*.*.tuberack.create'
  - '*.*.tuberack.updatetuberack'
  - '*.*.tuberack.deletetuberack'
  - '*.*.order.createorder'
  - '*.*.order.create'
  - '*.*.order.updateorder'
  - '*.*.platetransfer.platetransfer'
  - '*.*.transferplatestoplates.transferplatestoplates'
  - '*.*.tuberacktransfer.tuberacktransfer'
  - '*.*.tuberackmove.tuberackmove'
  - '*.*.labellable.createlabellable'
  - '*.*.labellable.create'
  - '*.*.bulkcreatelabellable.*'
  - '*.*.updatelabel.*'
  - '*.*.bulkupdatelabel.*'
  - '*.*.swapsamples.*'

sample_management:
  - '*.*.sample.createsample'
  - '*.*.sample.create'
  - '*.*.sample.updatesample'
  - '*.*.sample.deletesample'
  - '*.*.bulkcreatesample.*'
  - '*.*.bulkupdatesample.*'
  - '*.*.bulkdeletesample.*'
